log:
  path: D:\log\work\dev
  appName: dewls
  level: info
server:
  port: 8888
  connection-timeout: 120000

spring:
  jta:
      enabled: true
      atomikos:
        datasource:
          jta-user:
            xa-properties.url: jdbc:mysql://10.222.38.151:3306/dewls01?useUnicode=yes&characterEncoding=utf8&useSSL=true
            xa-properties.user: root
            xa-properties.password: 123
            xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
            unique-resource-name: jta-customer
            max-pool-size: 25
            min-pool-size: 3
            max-lifetime: 20000
            borrow-connection-timeout: 10000
          jta-product:
            xa-properties.url: jdbc:mysql://10.222.39.90:3306/dewls02?useUnicode=yes&characterEncoding=utf8&useSSL=true
            xa-properties.user: root
            xa-properties.password: root
            xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
            unique-resource-name: order
            max-pool-size: 25
            min-pool-size: 3
            max-lifetime: 20000
            borrow-connection-timeout: 10000
  jpa:
    show-sql: true
    database: MySQL
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
