create database dewls01;
create database dewls02;

CREATE TABLE `frm_student` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `SHAPE` VARCHAR(50) COLLATE utf8_bin DEFAULT NULL,
  `DESCRIPTION` VARCHAR(50) COLLATE utf8_bin DEFAULT NULL,
  `FRM_VERSION` BIGINT(20) NOT NULL,
  `JPA_VERSION` BIGINT(20) NOT NULL,
  `CREATE_BY` VARCHAR(15) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_CLIENT_ID` VARCHAR(65) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_IODT` VARCHAR(18) COLLATE utf8_bin DEFAULT NULL,
  `UPDATE_BY` VARCHAR(15) COLLATE utf8_bin DEFAULT NULL,
  `UPDATE_CLIENT_ID` VARCHAR(65) COLLATE utf8_bin DEFAULT NULL,
  `UPDATE_IODT` VARCHAR(18) COLLATE utf8_bin DEFAULT NULL,
  `REC_UPD_DT` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_bin

CREATE TABLE `PERSON` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(50) DEFAULT NULL,
  `LAST_NAME` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `USER` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) DEFAULT NULL,
  `EMAIL` VARCHAR(50) DEFAULT NULL,
  `AGE` BIGINT(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `PRODUCT` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) DEFAULT NULL,
  `PRICE` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


